'use client';

import { experiences } from '../data/portfolio';
import { Tags } from './ui';
import ExperienceReport from './experience-report';
import { useLanguage } from './language-context';
import { localizeExperience } from './content-translations';

const additionalExperiences=[
{id:'experience-ocp-2019',company:'OCP',logo:'/companies/ocp.png',department:'Office Chérifien des Phosphates — Laverie BA',role:'Stage Ingénieur',period:'Juillet 2019 – Août 2019',place:'Khouribga, Maroc',objectives:['Amélioration de la gestion et du contrôle du site Beni Amir.'],tasks:['Étude et communication de l’analyseur OUTOTEC avec le système de contrôle DCS.','Amélioration des boucles de régulation de l’unité de flottation par l’outil Matlab-Simulink.'],stack:['DCS','OUTOTEC','Matlab','Simulink','Régulation industrielle']},
{id:'experience-onda-2018',company:'Office National des Aéroports',logo:'/companies/onda.png',department:'Office National des Aéroports',role:'Stage Ingénieur d’initiation',period:'Juillet 2018 – Août 2018',place:'Casablanca, Maroc',objectives:['Étude d’installation d’une ligne de convoyage pour traitement des bagages.'],tasks:['Description générale de l’installation de traitement de bagages de l’arrivée et de correspondance.','Automatisation d’une nouvelle ligne de convoyage de traitement de bagages.'],stack:['Automatisation','Convoyage','Traitement des bagages','Systèmes industriels']}
];

const parcelMain={
fr:[{text:'Conception et développement des programmes et applications informatiques.',subs:['Conception d’un banc de test automatisé en Python/Raspberry Pi pour valider les fonctionnalités.','Mise en place d’une checklist complète équivalente à un catalogue d’essais.']},{text:'Élaboration et rédaction des spécifications techniques.'},{text:'Réalisation des tests techniques et fonctionnels des logiciels et applications.'},{text:'Analyse des problèmes techniques, fonctionnels et proposition de corrections.'},{text:'Interface régulière avec les responsables et l’équipe projet afin de présenter les résultats et de suivre la mise en œuvre des corrections.'},{text:'Interventions chez les utilisateurs à domicile :',subs:['Traitement des mails pour identifier les problèmes et besoins, suivi de la satisfaction client.','Élaboration d’un fichier Excel pour centraliser les informations liées aux interventions.','Réparation des boîtes, remplacement de cartes électroniques, mise à jour logicielle, changement de panneaux solaires et de batteries.','Rédaction sur place de rapports d’intervention.']},{text:'Collaboration avec les équipes de développement mobile :',subs:['Explication du fonctionnement de la boîte et de la construction des trames de données.','Réalisation de tests de l’application mobile.','Rédaction de rapports de tests destinés aux développeurs.']}],
en:[{text:'Design and development of software programs and applications.',subs:['Design of an automated Python/Raspberry Pi test bench to validate functionalities.','Implementation of a complete checklist equivalent to a test catalogue.']},{text:'Preparation and writing of technical specifications.'},{text:'Technical and functional testing of software and applications.'},{text:'Analysis of technical and functional issues and proposal of corrections.'},{text:'Regular coordination with managers and the project team to present results and track corrective actions.'},{text:'Interventions at users’ homes:',subs:['Process emails to identify issues and needs and monitor customer satisfaction.','Create an Excel file to centralise intervention information.','Repair parcel boxes, replace electronic boards, update software, and replace solar panels and batteries.','Write on-site intervention reports.']},{text:'Collaboration with mobile-development teams:',subs:['Explain how the parcel box works and how data frames are built.','Test the mobile application.','Write test reports for developers.']}],
es:[{text:'Diseño y desarrollo de programas y aplicaciones.',subs:['Diseño de un banco de pruebas automatizado en Python/Raspberry Pi.','Creación de una checklist completa equivalente a un catálogo de ensayos.']},{text:'Elaboración y redacción de especificaciones técnicas.'},{text:'Realización de pruebas técnicas y funcionales.'},{text:'Análisis de problemas técnicos y funcionales y propuesta de correcciones.'},{text:'Coordinación regular con responsables y equipo de proyecto para presentar resultados y seguir las correcciones.'},{text:'Intervenciones en el domicilio de usuarios:',subs:['Gestión de correos para identificar problemas y necesidades.','Creación de un archivo Excel para centralizar las intervenciones.','Reparación de buzones, sustitución de placas, actualización de software y cambio de paneles solares y baterías.','Redacción de informes de intervención in situ.']},{text:'Colaboración con los equipos de desarrollo móvil:',subs:['Explicación del funcionamiento del buzón y de las tramas de datos.','Pruebas de la aplicación móvil.','Redacción de informes de prueba para desarrolladores.']}],
de:[{text:'Entwicklung von Programmen und Anwendungen.',subs:['Entwicklung eines automatisierten Python/Raspberry-Pi-Teststands.','Erstellung einer vollständigen Test-Checkliste.']},{text:'Erstellung technischer Spezifikationen.'},{text:'Technische und funktionale Tests von Software und Anwendungen.'},{text:'Analyse technischer und funktionaler Probleme und Vorschlag von Korrekturen.'},{text:'Regelmäßige Abstimmung mit Verantwortlichen und Projektteam zur Präsentation der Ergebnisse und Nachverfolgung von Korrekturen.'},{text:'Einsätze bei Nutzern zu Hause:',subs:['E-Mails bearbeiten, um Probleme und Bedürfnisse zu identifizieren.','Excel-Datei zur Zentralisierung der Interventionsdaten erstellen.','Paketboxen reparieren, Platinen ersetzen, Software aktualisieren sowie Solarpanels und Batterien wechseln.','Interventionsberichte vor Ort schreiben.']},{text:'Zusammenarbeit mit Mobile-Entwicklungsteams:',subs:['Funktionsweise der Box und Aufbau der Datenframes erklären.','Mobile App testen.','Testberichte für Entwickler verfassen.']}],
ar:[{text:'تصميم وتطوير البرامج والتطبيقات.',subs:['تصميم منصة اختبار آلية باستخدام Python وRaspberry Pi للتحقق من الوظائف.','إعداد قائمة فحص كاملة تعادل كتالوج اختبارات.']},{text:'إعداد وكتابة المواصفات التقنية.'},{text:'إجراء الاختبارات التقنية والوظيفية للبرامج والتطبيقات.'},{text:'تحليل المشاكل التقنية والوظيفية واقتراح التصحيحات.'},{text:'التنسيق المنتظم مع المسؤولين وفريق المشروع لعرض النتائج ومتابعة تنفيذ التصحيحات.'},{text:'التدخل لدى المستخدمين في المنازل:',subs:['معالجة الرسائل لتحديد المشاكل والاحتياجات ومتابعة رضا العملاء.','إنشاء ملف Excel لمركزة معلومات التدخلات.','إصلاح الصناديق واستبدال اللوحات الإلكترونية وتحديث البرمجيات وتغيير الألواح الشمسية والبطاريات.','كتابة تقارير التدخل في الموقع.']},{text:'التعاون مع فرق تطوير تطبيقات الهاتف:',subs:['شرح عمل الصندوق وبناء إطارات البيانات.','اختبار تطبيق الهاتف.','كتابة تقارير الاختبار للمطورين.']}]
};

const parcelStage={
fr:[{title:'Sujet 1 : Réalisation d’un banc de test :',items:['Analyse des spécifications techniques et cahier des charges.','Création d’une interface graphique capable d’interagir avec la boîte à colis intelligente via BLE, développée en Python sur Raspberry Pi.','Génération automatique d’une check-list et rédaction d’un rapport de test.','Acquisition des données et décryptage avec Protobuf.','Récupération des logs et envoi au serveur.','Test des services de l’API et de la communication avec la boîte.']},{title:'Sujet 2 : Identification d’une solution hardware capable de contrôler en ligne l’équipement de l’entreprise :',items:['Identification d’une solution hardware pour contrôler la boîte en ligne.','Réalisation d’un prototype de passerelle Wi-Fi / Bluetooth.','Établissement de la connexion Bluetooth avec la boîte intelligente.','Création d’une page web contenant toutes les commandes de la boîte intelligente.','Configuration des paramètres Wi-Fi via Bluetooth à l’aide d’une application mobile.']}],
en:[{title:'Topic 1: Building a test bench:',items:['Analyse technical specifications and requirements.','Create a Python/Raspberry Pi graphical interface interacting with the smart parcel box via BLE.','Automatically generate a checklist and write a test report.','Acquire and decode data using Protobuf.','Retrieve logs and send them to the server.','Test API services and communication with the box.']},{title:'Topic 2: Identifying a hardware solution for online control:',items:['Identify a hardware solution for remote control.','Build a Wi-Fi/Bluetooth gateway prototype.','Establish the Bluetooth connection with the smart box.','Create a web page containing all box commands.','Configure Wi-Fi parameters via Bluetooth using a mobile application.']}],
es:[{title:'Tema 1: Realización de un banco de pruebas:',items:['Analizar especificaciones y requisitos.','Crear una interfaz Python/Raspberry Pi que interactúe con el buzón mediante BLE.','Generar automáticamente una checklist y redactar un informe de prueba.','Adquirir y decodificar datos con Protobuf.','Recuperar logs y enviarlos al servidor.','Probar servicios API y comunicación con el buzón.']},{title:'Tema 2: Identificación de una solución hardware para control en línea:',items:['Identificar una solución hardware para control remoto.','Crear un prototipo de pasarela Wi-Fi/Bluetooth.','Establecer la conexión Bluetooth.','Crear una página web con todos los comandos.','Configurar Wi-Fi mediante Bluetooth con una aplicación móvil.']}],
de:[{title:'Thema 1: Aufbau eines Teststands:',items:['Technische Spezifikationen und Lastenheft analysieren.','Python/Raspberry-Pi-Oberfläche zur BLE-Kommunikation mit der Paketbox erstellen.','Checkliste automatisch erzeugen und Testbericht schreiben.','Daten mit Protobuf erfassen und dekodieren.','Logs abrufen und an den Server senden.','API-Dienste und Box-Kommunikation testen.']},{title:'Thema 2: Hardwarelösung für die Online-Steuerung:',items:['Hardwarelösung zur Fernsteuerung identifizieren.','Wi-Fi/Bluetooth-Gateway-Prototyp erstellen.','Bluetooth-Verbindung herstellen.','Webseite mit allen Box-Befehlen erstellen.','Wi-Fi-Parameter per Bluetooth über eine mobile App konfigurieren.']}],
ar:[{title:'الموضوع 1: إنجاز منصة اختبار:',items:['تحليل المواصفات التقنية ودفتر التحملات.','إنشاء واجهة Python/Raspberry Pi للتفاعل مع الصندوق الذكي عبر BLE.','إنشاء قائمة فحص تلقائياً وكتابة تقرير اختبار.','استخراج البيانات وفكها باستخدام Protobuf.','استرجاع السجلات وإرسالها إلى الخادم.','اختبار خدمات API والاتصال بالصندوق.']},{title:'الموضوع 2: تحديد حل هاردوير للتحكم عن بعد:',items:['تحديد حل هاردوير للتحكم في الصندوق عن بعد.','إنجاز نموذج أولي لبوابة Wi-Fi/Bluetooth.','إنشاء اتصال Bluetooth مع الصندوق.','إنشاء صفحة ويب تحتوي جميع أوامر الصندوق.','إعداد Wi-Fi عبر Bluetooth باستخدام تطبيق هاتف.']}]
};

const tagMap={en:{'Régulation industrielle':'Industrial Control','Automatisation':'Automation','Convoyage':'Conveying','Traitement des bagages':'Baggage Handling','Systèmes industriels':'Industrial Systems','Supervision industrielle':'Industrial Supervision','Automate Siemens S7-200':'Siemens S7-200 PLC'},es:{'Régulation industrielle':'Control industrial','Automatisation':'Automatización','Convoyage':'Transporte','Traitement des bagages':'Tratamiento de equipajes','Systèmes industriels':'Sistemas industriales','Supervision industrielle':'Supervisión industrial','Automate Siemens S7-200':'PLC Siemens S7-200'},de:{'Régulation industrielle':'Industrielle Regelung','Automatisation':'Automatisierung','Convoyage':'Fördertechnik','Traitement des bagages':'Gepäckabfertigung','Systèmes industriels':'Industriesysteme','Supervision industrielle':'Industrieüberwachung','Automate Siemens S7-200':'Siemens S7-200 SPS'},ar:{'Régulation industrielle':'التحكم الصناعي','Automatisation':'الأتمتة','Convoyage':'أنظمة النقل','Traitement des bagages':'معالجة الأمتعة','Systèmes industriels':'الأنظمة الصناعية','Supervision industrielle':'المراقبة الصناعية','Automate Siemens S7-200':'متحكم Siemens S7-200'}};
function displayName(e){if(e.id==='experience-alstom')return'ALSTOM';if(e.id==='experience-continental')return'CONTINENTAL';if(e.id.startsWith('experience-parcelhome'))return'ParcelHome';if(e.id.startsWith('experience-ocp'))return'OCP';if(e.id==='experience-onda-2018')return'ONDA';return e.company}
function translateStack(stack,language){if(language==='fr')return stack;return stack.map(x=>tagMap[language]?.[x]||x)}
function ParcelAchievements({language}){return <ul className="achievementList achievementListMain">{parcelMain[language].map((item,i)=><li key={i}>{item.text}{item.subs&&<ul className="achievementSubList">{item.subs.map((s,j)=><li key={j}>{s}</li>)}</ul>}</li>)}</ul>}
function ParcelStageAchievements({language}){return <div className="parcelSubjects">{parcelStage[language].map((subject,i)=><div className="parcelSubject" key={i}><h6>{subject.title}</h6><ul className="achievementList">{subject.items.map((s,j)=><li key={j}>{s}</li>)}</ul></div>)}</div>}
function Achievements({experience,language}){if(experience.id==='experience-parcelhome')return <ParcelAchievements language={language}/>;if(experience.id==='experience-parcelhome-stage')return <ParcelStageAchievements language={language}/>;return <ul>{experience.tasks.map((x,i)=><li key={i}>{x}</li>)}</ul>}

export default function ExperienceSection(){const{language,t}=useLanguage();const all=[...experiences,...additionalExperiences].map(e=>localizeExperience(e,language));return <section id="experience" className="section shell"><h2>{t('professionalExp').toUpperCase()}</h2><div className="timeline">{all.map(e=><article className="experience experienceRefined" id={e.id} key={e.id}><div className="experienceBody"><div className="experienceTopRow"><div className="experienceIdentity"><div className="experienceLogoInline"><img src={e.logo} alt={`Logo ${displayName(e)}`} loading="lazy"/></div><div><h3>{displayName(e)}</h3><p className="experienceDepartment">{e.department}</p></div></div><div className="experienceTopActions"><div className="experienceMetaTop"><strong>{e.id==='experience-alstom'&&language==='fr'?'Juillet 2024 – Octobre 2025':e.period}</strong><span>{e.place}</span></div><ExperienceReport experienceId={e.id} title={displayName(e)}/></div></div><h4>{e.role}</h4><div className="experienceBlock"><h5>{t('objectives')}</h5><ul>{e.objectives.map((x,i)=><li key={i}>{x}</li>)}</ul></div><div className="experienceBlock"><h5>{t('achievements')}</h5><Achievements experience={e} language={language}/></div><div className="experienceBlock"><h5>{t('environment')}</h5><Tags items={translateStack(e.stack,language)}/></div></div></article>)}</div></section>}
