'use client';

import { experiences } from '../data/portfolio';
import { Tags } from './ui';
import ExperienceReport from './experience-report';
import { useLanguage } from './language-context';
import { localizeExperience } from './content-translations';

const additionalExperiences=[
{id:'experience-ocp-2019',company:'OCP',logo:'/companies/ocp.png',department:'Office Chérifien des Phosphates — Laverie BA',role:'Stage Ingénieur',period:'Juillet 2019 – Août 2019',place:'Khouribga, Maroc',objectives:['Amélioration de la gestion et du contrôle du site Beni Amir.'],tasks:['Étude et communication de l’analyseur OUTOTEC avec le système de contrôle DCS.','Amélioration des boucles de régulation de l’unité de flottation par l’outil Matlab-Simulink.'],stack:['DCS','OUTOTEC','Matlab','Simulink','Régulation industrielle']},
{id:'experience-onda-2018',company:'Office National des Aéroports',logo:'/companies/onda.png',department:'Office National des Aéroports',role:'Stage Ingénieur d’initiation',period:'Juillet 2018 – Août 2018',place:'Casablanca, Maroc',objectives:['Étude d’installation d’une ligne de convoyage pour traitement des bagages.'],tasks:['Description générale de l’installation de traitement de bagages de l’arrivée et de correspondance.','Automatisation d’une nouvelle ligne de convoyage de traitement de bagages.'],stack:['Automatisation','Convoyage','Traitement des bagages','Systèmes industriels']}
];
const tagMap={en:{'Régulation industrielle':'Industrial Control','Automatisation':'Automation','Convoyage':'Conveying','Traitement des bagages':'Baggage Handling','Systèmes industriels':'Industrial Systems','Supervision industrielle':'Industrial Supervision','Automate Siemens S7-200':'Siemens S7-200 PLC'},es:{'Régulation industrielle':'Control industrial','Automatisation':'Automatización','Convoyage':'Transporte','Traitement des bagages':'Tratamiento de equipajes','Systèmes industriels':'Sistemas industriales','Supervision industrielle':'Supervisión industrial','Automate Siemens S7-200':'PLC Siemens S7-200'},de:{'Régulation industrielle':'Industrielle Regelung','Automatisation':'Automatisierung','Convoyage':'Fördertechnik','Traitement des bagages':'Gepäckabfertigung','Systèmes industriels':'Industriesysteme','Supervision industrielle':'Industrieüberwachung','Automate Siemens S7-200':'Siemens S7-200 SPS'},ar:{'Régulation industrielle':'التحكم الصناعي','Automatisation':'الأتمتة','Convoyage':'أنظمة النقل','Traitement des bagages':'معالجة الأمتعة','Systèmes industriels':'الأنظمة الصناعية','Supervision industrielle':'المراقبة الصناعية','Automate Siemens S7-200':'متحكم Siemens S7-200'}};
function displayName(e){if(e.id==='experience-alstom')return'ALSTOM';if(e.id==='experience-continental')return'CONTINENTAL';if(e.id.startsWith('experience-parcelhome'))return'ParcelHome';if(e.id.startsWith('experience-ocp'))return'OCP';if(e.id==='experience-onda-2018')return'ONDA';return e.company}
function translateStack(stack,language){if(language==='fr')return stack;return stack.map(x=>tagMap[language]?.[x]||x)}
export default function ExperienceSection(){const{language,t}=useLanguage();const all=[...experiences,...additionalExperiences].map(e=>localizeExperience(e,language));return <section id="experience" className="section shell"><h2>{t('professionalExp').toUpperCase()}</h2><div className="timeline">{all.map(e=><article className="experience experienceRefined" id={e.id} key={e.id}><div className="experienceBody"><div className="experienceTopRow"><div className="experienceIdentity"><div className="experienceLogoInline"><img src={e.logo} alt={`Logo ${displayName(e)}`} loading="lazy"/></div><div><h3>{displayName(e)}</h3><p className="experienceDepartment">{e.department}</p></div></div><div className="experienceTopActions"><div className="experienceMetaTop"><strong>{e.id==='experience-alstom'&&language==='fr'?'Juillet 2024 – Octobre 2025':e.period}</strong><span>{e.place}</span></div><ExperienceReport experienceId={e.id} title={displayName(e)}/></div></div><h4>{e.role}</h4><div className="experienceBlock"><h5>{t('objectives')}</h5><ul>{e.objectives.map((x,i)=><li key={i}>{x}</li>)}</ul></div><div className="experienceBlock"><h5>{t('achievements')}</h5><ul className={e.id.startsWith('experience-parcelhome')?'achievementList':''}>{e.tasks.map((x,i)=><li key={i}>{x}</li>)}</ul></div><div className="experienceBlock"><h5>{t('environment')}</h5><Tags items={translateStack(e.stack,language)}/></div></div></article>)}</div></section>}
