'use client';

import { useEffect, useState } from 'react';
import { languages, useLanguage } from './language-context';

function ThemeIcon({ type }) { if(type==='moon')return <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M21 12.8A8.5 8.5 0 1 1 11.2 3 6.7 6.7 0 0 0 21 12.8Z"/></svg>; return <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="12" cy="12" r="3"/><path d="M12 2v2M12 20v2M4.9 4.9l1.4 1.4M17.7 17.7l1.4 1.4M2 12h2M20 12h2M4.9 19.1l1.4-1.4M17.7 6.3l1.4-1.4"/></svg> }

export default function Navigation(){
 const {language,setLanguage,t}=useLanguage();
 const links=[['#about','navAbout'],['#experience','navExperience'],['#projects','navProjects'],['#awards','navAwards'],['#data','navData'],['#certifications','navCerts'],['#education','navEducation'],['#contact','navContact']];
 const[active,setActive]=useState('#about');const[menuOpen,setMenuOpen]=useState(false);
 useEffect(()=>{let ticking=false;const update=()=>{let current=links[0][0];for(const [href] of links){const s=document.querySelector(href);if(s&&s.getBoundingClientRect().top<=130)current=href}if(window.innerHeight+window.scrollY>=document.documentElement.scrollHeight-8)current='#contact';setActive(current);ticking=false};const onScroll=()=>{if(!ticking){requestAnimationFrame(update);ticking=true}};update();addEventListener('scroll',onScroll,{passive:true});addEventListener('resize',onScroll);return()=>{removeEventListener('scroll',onScroll);removeEventListener('resize',onScroll)}},[language]);
 return <header className="navBar"><nav className="nav shell" aria-label="Navigation"><a className="brand" href="#top">OE<span>.</span></a><div className="navRight"><div className="navlinks">{links.map(([href,key])=><a key={href} className={active===href?'active':''} href={href} onClick={()=>{setActive(href);setMenuOpen(false)}}>{t(key)}</a>)}</div><div className="languageSelector"><span aria-hidden="true">🌐</span><select aria-label={t('language')} value={language} onChange={e=>setLanguage(e.target.value)}>{languages.map(l=><option key={l.code} value={l.code}>{l.label}</option>)}</select></div><div className="themeToggle" aria-label="Theme"><span><ThemeIcon type="moon"/></span><span className="themeActive"><ThemeIcon type="sun"/></span></div><button className={`mobileMenuButton ${menuOpen?'open':''}`} type="button" aria-expanded={menuOpen} onClick={()=>setMenuOpen(v=>!v)}><span/><span/><span/></button></div></nav><div className={`mobileMenu ${menuOpen?'open':''}`}><div className="mobileMenuInner shell">{links.map(([href,key])=><a key={href} className={active===href?'active':''} href={href} onClick={()=>{setActive(href);setMenuOpen(false)}}>{t(key)}</a>)}</div></div></header>
}
